// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RN77.BD.Datos;

namespace RN77.BD.Migrations
{
    [DbContext(typeof(RN77Context))]
    partial class RN77ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaAlumnos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AulaId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("PersonaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AulaAlumnos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaAsistencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actividades")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<int>("AulaAlumnoId");

                    b.Property<int?>("AulaTemaClaseId");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("NumUnidad")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("TipoClase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AulaAlumnoId");

                    b.HasIndex("AulaTemaClaseId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AulaAsistencias");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaDocentes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AulaId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("PersonaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AulaDocentes");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaEvaluaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AulaId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<byte>("SePromedia");

                    b.Property<string>("TipoEvaluacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AulaEvaluaciones");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaGrupoAlumnos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AulaAlumnoId");

                    b.Property<int>("AulaGrupoId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AulaAlumnoId");

                    b.HasIndex("AulaGrupoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AulaGrupoAlumnos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaGrupos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AulaId");

                    b.Property<int>("CharlaId");

                    b.Property<string>("CodigoGrupo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("CharlaId");

                    b.HasIndex("CodigoGrupo")
                        .IsUnique()
                        .HasName("IQ_AulaGrupos");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AulaGrupos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaNotas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AulaAlumnoId");

                    b.Property<int?>("AulaEvaluacionId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("AulaAlumnoId");

                    b.HasIndex("AulaEvaluacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AulaNotas");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaTemaClases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actividades")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<int>("AulaId");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("NumUnidad")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("TipoClase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AulaTemaClases");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Aulas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoLectivo");

                    b.Property<int?>("AsistenciaValidaId");

                    b.Property<int?>("CarreraId");

                    b.Property<int?>("CarreraMateriaId");

                    b.Property<int?>("CharlaId");

                    b.Property<string>("CodigoAula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<DateTime?>("Desde")
                        .HasColumnType("date");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<DateTime?>("Hasta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int?>("NotasValidaId");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("CarreraMateriaId");

                    b.HasIndex("CharlaId");

                    b.HasIndex("CodigoAula")
                        .IsUnique()
                        .HasName("IQ_Aulas");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CarreraMaterias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarreraId");

                    b.Property<int>("CarreraMateriaId");

                    b.Property<string>("CodigoMateria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("CarreraMateriaId");

                    b.HasIndex("CodigoMateria")
                        .IsUnique()
                        .HasName("IQ_CarreraMaterias");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CarreraMaterias");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Carreras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoCarrera")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<int>("InstitucionId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CodigoCarrera")
                        .IsUnique()
                        .HasName("IQ_Carreras");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaDigoArchivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharlaDigoId");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("Path")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CharlaDigoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CharlaDigoArchivos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaDigoLinks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharlaDigoId");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Link")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CharlaDigoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CharlaDigoLinks");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaDigos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharlaDigoDeDigoId");

                    b.Property<int>("CharlaId");

                    b.Property<int>("CharlaPersonaId");

                    b.Property<string>("Digo")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaDigo")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CharlaDigoDeDigoId");

                    b.HasIndex("CharlaId");

                    b.HasIndex("CharlaPersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CharlaDigos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaLeeDigos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharlaDigoId");

                    b.Property<int>("CharlaPersonaId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime?>("FechaLeo")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<DateTime>("FechaNotifico")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRecibe")
                        .HasColumnType("datetime");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CharlaDigoId");

                    b.HasIndex("CharlaPersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CharlaLeeDigos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaPersonas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharlaId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("PersonaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CharlaId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CharlaPersonas");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Charlas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoCharla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("PathLogo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<int>("TcharlaId")
                        .HasColumnName("TCharlaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CodigoCharla")
                        .IsUnique()
                        .HasName("IQ_Charlas");

                    b.HasIndex("TcharlaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Charlas");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Ciudades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("NombreCiudad")
                        .IsRequired();

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("ProvinciaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("NombreCiudad")
                        .IsUnique()
                        .HasName("IQ_NombreCiudad");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Documentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("TdocumentoId")
                        .HasColumnName("TDocumentoId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("TdocumentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Domicilios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int>("CiudadId")
                        .HasColumnName("CiudadId");

                    b.Property<string>("Cp")
                        .IsRequired()
                        .HasColumnName("CP")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Dpto")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("Piso")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int>("TdomicilioId")
                        .HasColumnName("TDomicilioId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("TdomicilioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.InstitucionDocumentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocumentoId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<int>("InstitucionId");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("InstitucionDocumentos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.InstitucionDomicilios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DomicilioId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<int>("InstitucionId");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DomicilioId");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("InstitucionDomicilios");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.InstitucionMails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<int>("InstitucionId");

                    b.Property<int>("MailId");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("MailId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("InstitucionMails");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.InstitucionTels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<int>("InstitucionId");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("TelId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("TelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("InstitucionTels");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Instituciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoInstitucion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("TnotaId")
                        .HasColumnName("TNotaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CodigoInstitucion")
                        .IsUnique()
                        .HasName("IQ_Instituciones");

                    b.HasIndex("TnotaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Mails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("TmailId")
                        .HasColumnName("TMailId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("TmailId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Materias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Paises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("NombrePais")
                        .IsRequired();

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CodigoPais")
                        .IsUnique()
                        .HasName("IQ_CodigoPais");

                    b.HasIndex("NombrePais")
                        .IsUnique()
                        .HasName("IQ_NombrePais");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.PersonaDocumentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocumentoId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("PersonaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PersonaDocumentos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.PersonaDomicilios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DomicilioId");

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("PersonaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DomicilioId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PersonaDomicilios");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.PersonaMails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<int>("MailId");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("PersonaId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("MailId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PersonaMails");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.PersonaTels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("PersonaId");

                    b.Property<int>("TelId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PersonaTels");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Personas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Provincias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("NombreProvincia")
                        .IsRequired();

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("PaisId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("NombreProvincia")
                        .IsUnique()
                        .HasName("IQ_NombreProvincia");

                    b.HasIndex("PaisId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tcharlas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasName("IQ_Tcharlas");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tcharlas");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tdocumentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasName("IX_TDocumentos");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tdocumentos");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tdomicilios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasName("IX_TDomicilio");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tdomicilios");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int>("TtelId")
                        .HasColumnName("TTelId");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("TtelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tels");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tmails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasName("IQ_TMails");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tmails");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tnotas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<int>("Paso");

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.Property<string>("ValorMax")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("ValorMin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasName("IQ_Tnotas");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tnotas");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Ttels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<byte>("EstadoReg");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("ObservReg")
                        .IsRequired();

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasName("IQ_Ttels");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ttels");
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Usuarios", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<DateTime?>("FechaBajaReg");

                    b.Property<DateTime>("FechaCreaReg");

                    b.Property<DateTime>("FechaModifReg");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<int?>("PersonaId");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaAlumnos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Aulas", "Aula")
                        .WithMany("AulaAlumnos")
                        .HasForeignKey("AulaId")
                        .HasConstraintName("FK_AulaAlumnos_Aulas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Personas", "Persona")
                        .WithMany("AulaAlumnos")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_AulaAlumnos_Personas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaAsistencias", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.AulaAlumnos", "AulaAlumno")
                        .WithMany("AulaAsistencias")
                        .HasForeignKey("AulaAlumnoId")
                        .HasConstraintName("FK_AulaAsistencias_AulaAlumnos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.AulaTemaClases", "AulaTemaClase")
                        .WithMany("AulaAsistencias")
                        .HasForeignKey("AulaTemaClaseId")
                        .HasConstraintName("FK_AulaAsistencias_AulaTemaClases");

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaDocentes", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Aulas", "Aula")
                        .WithMany("AulaDocentes")
                        .HasForeignKey("AulaId")
                        .HasConstraintName("FK_AulaDocentes_Aulas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Personas", "Persona")
                        .WithMany("AulaDocentes")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_AulaDocentes_Personas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaEvaluaciones", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Aulas", "Aula")
                        .WithMany("AulaEvaluaciones")
                        .HasForeignKey("AulaId")
                        .HasConstraintName("FK_AulaEvaluaciones_Aulas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaGrupoAlumnos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.AulaAlumnos", "AulaAlumno")
                        .WithMany("AulaGrupoAlumnos")
                        .HasForeignKey("AulaAlumnoId")
                        .HasConstraintName("FK_AulaGrupoAlumnos_AulaAlumnos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.AulaGrupos", "AulaGrupo")
                        .WithMany("AulaGrupoAlumnos")
                        .HasForeignKey("AulaGrupoId")
                        .HasConstraintName("FK_AulaGrupoAlumnos_AulaGrupos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaGrupos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Aulas", "Aula")
                        .WithMany("AulaGrupos")
                        .HasForeignKey("AulaId")
                        .HasConstraintName("FK_AulaGrupos_Aulas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Charlas", "Charla")
                        .WithMany("AulaGrupos")
                        .HasForeignKey("CharlaId")
                        .HasConstraintName("FK_AulaGrupos_Charlas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaNotas", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.AulaAlumnos", "AulaAlumno")
                        .WithMany("AulaNotas")
                        .HasForeignKey("AulaAlumnoId")
                        .HasConstraintName("FK_AulaNotas_AulaAlumnos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.AulaEvaluaciones", "AulaEvaluacion")
                        .WithMany("AulaNotas")
                        .HasForeignKey("AulaEvaluacionId")
                        .HasConstraintName("FK_AulaNotas_AulaEvaluaciones");

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.AulaTemaClases", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Aulas", "Aula")
                        .WithMany("AulaTemaClases")
                        .HasForeignKey("AulaId")
                        .HasConstraintName("FK_AulaTemaClases_Aulas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Aulas", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Carreras", "Carrera")
                        .WithMany("Aulas")
                        .HasForeignKey("CarreraId")
                        .HasConstraintName("FK_Aulas_Carreras");

                    b.HasOne("RN77.BD.Datos.Entities.CarreraMaterias", "CarreraMateria")
                        .WithMany("Aulas")
                        .HasForeignKey("CarreraMateriaId")
                        .HasConstraintName("FK_Aulas_CarreraMaterias");

                    b.HasOne("RN77.BD.Datos.Entities.Charlas", "Charla")
                        .WithMany("Aulas")
                        .HasForeignKey("CharlaId")
                        .HasConstraintName("FK_Aulas_Charlas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CarreraMaterias", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Carreras", "Carrera")
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("CarreraId")
                        .HasConstraintName("FK_CarreraMaterias_Carreras")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Materias", "CarreraMateria")
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("CarreraMateriaId")
                        .HasConstraintName("FK_CarreraMaterias_Materias")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Carreras", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Instituciones", "Institucion")
                        .WithMany("Carreras")
                        .HasForeignKey("InstitucionId")
                        .HasConstraintName("FK_Carreras_Instituciones")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaDigoArchivos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.CharlaDigos", "CharlaDigo")
                        .WithMany("CharlaDigoArchivos")
                        .HasForeignKey("CharlaDigoId")
                        .HasConstraintName("FK_CharlaDigoArchivoss_CharlaDigos");

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaDigoLinks", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.CharlaDigos", "CharlaDigo")
                        .WithMany("CharlaDigoLinks")
                        .HasForeignKey("CharlaDigoId")
                        .HasConstraintName("FK_CharlaDigoLinks_CharlaDigos");

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaDigos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.CharlaDigos", "CharlaDigoDeDigo")
                        .WithMany("InverseCharlaDigoDeDigo")
                        .HasForeignKey("CharlaDigoDeDigoId")
                        .HasConstraintName("FK_CharlaDigos_CharlaDigos");

                    b.HasOne("RN77.BD.Datos.Entities.Charlas", "Charla")
                        .WithMany("CharlaDigos")
                        .HasForeignKey("CharlaId")
                        .HasConstraintName("FK_CharlaDigos_Charlas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.CharlaPersonas", "CharlaPersona")
                        .WithMany("CharlaDigos")
                        .HasForeignKey("CharlaPersonaId")
                        .HasConstraintName("FK_CharlaDigos_CharlaPersonas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaLeeDigos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.CharlaDigos", "CharlaDigo")
                        .WithMany("CharlaLeeDigos")
                        .HasForeignKey("CharlaDigoId")
                        .HasConstraintName("FK_CharlaLeeDigos_CharlaDigos");

                    b.HasOne("RN77.BD.Datos.Entities.CharlaPersonas", "CharlaPersona")
                        .WithMany("CharlaLeeDigos")
                        .HasForeignKey("CharlaPersonaId")
                        .HasConstraintName("FK_CharlaLeeDigos_CharlaPersonas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.CharlaPersonas", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Charlas", "Charla")
                        .WithMany("CharlaPersonas")
                        .HasForeignKey("CharlaId")
                        .HasConstraintName("FK_CharlaPersonas_Charlas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Personas", "Persona")
                        .WithMany("CharlaPersonas")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_CharlaPersonas_Personas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Charlas", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Tcharlas", "Tcharla")
                        .WithMany("Charlas")
                        .HasForeignKey("TcharlaId")
                        .HasConstraintName("FK_Charlas_TCharlas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Ciudades", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Provincias", "Provincia")
                        .WithMany("Ciudades")
                        .HasForeignKey("ProvinciaId")
                        .HasConstraintName("FK_Ciudades_Provincias")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Documentos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Tdocumentos", "Tdocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TdocumentoId")
                        .HasConstraintName("FK_Documentos_TDocumentos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Domicilios", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Ciudades", "Ciudad")
                        .WithMany("Domicilios")
                        .HasForeignKey("CiudadId")
                        .HasConstraintName("FK_Domicilios_Ciudades")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Tdomicilios", "Tdomicilio")
                        .WithMany("Domicilios")
                        .HasForeignKey("TdomicilioId")
                        .HasConstraintName("FK_Domicilios_TDomicilios")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.InstitucionDocumentos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Documentos", "Documento")
                        .WithMany("InstitucionDocumentos")
                        .HasForeignKey("DocumentoId")
                        .HasConstraintName("FK_InstitucionDocumentos_Documentos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Instituciones", "Institucion")
                        .WithMany("InstitucionDocumentos")
                        .HasForeignKey("InstitucionId")
                        .HasConstraintName("FK_InstitucionDocumentos_Instituciones")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.InstitucionDomicilios", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Domicilios", "Domicilio")
                        .WithMany("InstitucionDomicilios")
                        .HasForeignKey("DomicilioId")
                        .HasConstraintName("FK_InstitucionDomicilios_Domicilios")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Instituciones", "Institucion")
                        .WithMany("InstitucionDomicilios")
                        .HasForeignKey("InstitucionId")
                        .HasConstraintName("FK_InstitucionDomicilios_Instituciones")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.InstitucionMails", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Instituciones", "Institucion")
                        .WithMany("InstitucionMails")
                        .HasForeignKey("InstitucionId")
                        .HasConstraintName("FK_InstitucionMails_Instituciones")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Mails", "Mail")
                        .WithMany("InstitucionMails")
                        .HasForeignKey("MailId")
                        .HasConstraintName("FK_InstitucionMails_Mails")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.InstitucionTels", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Instituciones", "Institucion")
                        .WithMany("InstitucionTels")
                        .HasForeignKey("InstitucionId")
                        .HasConstraintName("FK_InstitucionTels_Instituciones")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Tels", "Tel")
                        .WithMany("InstitucionTels")
                        .HasForeignKey("TelId")
                        .HasConstraintName("FK_InstitucionTels_Tels")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Instituciones", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Tnotas", "Tnota")
                        .WithMany("Instituciones")
                        .HasForeignKey("TnotaId")
                        .HasConstraintName("FK_Instituciones_TNotas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Mails", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Tmails", "Tmail")
                        .WithMany("Mails")
                        .HasForeignKey("TmailId")
                        .HasConstraintName("FK_Mails_TMails")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Materias", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Paises", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.PersonaDocumentos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Documentos", "Documento")
                        .WithMany("PersonaDocumentos")
                        .HasForeignKey("DocumentoId")
                        .HasConstraintName("FK_PersonaDocumentos_Documentos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Personas", "Persona")
                        .WithMany("PersonaDocumentos")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_PersonaDocumentos_Personas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.PersonaDomicilios", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Domicilios", "Domicilio")
                        .WithMany("PersonaDomicilios")
                        .HasForeignKey("DomicilioId")
                        .HasConstraintName("FK_PersonaDomicilios_Domicilios")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Personas", "Persona")
                        .WithMany("PersonaDomicilios")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_PersonaDomicilios_Personas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.PersonaMails", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Mails", "Mail")
                        .WithMany("PersonaMails")
                        .HasForeignKey("MailId")
                        .HasConstraintName("FK_PersonaMails_Mails")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Personas", "Persona")
                        .WithMany("PersonaMails")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_PersonaMails_Personas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.PersonaTels", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Personas", "Persona")
                        .WithMany("PersonaTels")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_PersonaTels_Personas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Tels", "Tel")
                        .WithMany("PersonaTels")
                        .HasForeignKey("TelId")
                        .HasConstraintName("FK_PersonaTels_Tels")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Personas", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Provincias", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Paises", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisId")
                        .HasConstraintName("FK_Provincias_Paises")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tcharlas", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tdocumentos", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tdomicilios", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tels", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Ttels", "Ttel")
                        .WithMany("Tels")
                        .HasForeignKey("TtelId")
                        .HasConstraintName("FK_Tels_TTels")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tmails", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Tnotas", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RN77.BD.Datos.Entities.Ttels", b =>
                {
                    b.HasOne("RN77.BD.Datos.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
